# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

segment <- function(text, path) {
    .Call(`_RcppKyTea_segment`, text, path)
}

# Register entry points for exported C++ functions
methods::setLoadAction(function(ns) {
    .Call('_RcppKyTea_RcppExport_registerCCallable', PACKAGE = 'RcppKyTea')
})
